export const LOCATIONS = [
  {
    id: 'dp',
    name: 'Dana Porter Library',
    category: 'library',
    waitzUrl: 'https://waitz.io',
  },
  {
    id: 'dc',
    name: 'Davis Centre Library',
    category: 'library',
    waitzUrl: 'https://waitz.io',
  },
  { id: 'bloomberg', name: 'Bloomberg Finance Lab', capacity: 25, category: 'study' },
  { id: 'cmh', name: 'CMH Great Hall', capacity: 60, category: 'study' },
  { id: 'e5f3', name: 'E5 Floor 3', capacity: 20, category: 'study' },
  { id: 'e7ece5', name: 'E7 5th Floor ECE Lobby', capacity: 30, category: 'study' },
  { id: 'e7syde6', name: 'E7 6th Floor SYDE Lobby', capacity: 27, category: 'study' },
  { id: 'e7ece', name: 'E7 ECE Lounge', capacity: 27, category: 'study' },
  { id: 'e7quiet', name: 'E7 Quiet Study', capacity: 75, category: 'study' },
  { id: 'ev1', name: 'EV1 Atrium', capacity: 60, category: 'study' },
  { id: 'ev3f3', name: 'EV3 3rd Floor Student Commons', capacity: 25, category: 'study' },
  { id: 'ev3f4', name: 'EV3 4th Floor Student Commons', capacity: 25, category: 'study' },
  { id: 'hh2', name: 'HH 2nd Floor Study Commons', capacity: 20, category: 'study' },
  { id: 'hh3', name: 'HH 3rd Floor Study Commons', capacity: 25, category: 'study' },
  { id: 'hhfrl', name: 'HH Financial Research & Learning Lab', capacity: 35, category: 'study' },
  { id: 'hhfh', name: 'HH Founders Hall', capacity: 55, category: 'study' },
  { id: 'hlth', name: 'HLTH Silent Study', capacity: 40, category: 'study' },
  { id: 'mc2061', name: 'MC 2061', capacity: 36, category: 'study' },
  { id: 'mc2063', name: 'MC 2063', capacity: 36, category: 'study' },
  { id: 'mccomfy', name: 'MC Comfy Hours Lounge', capacity: 45, category: 'study' },
  { id: 'mcmac', name: 'MC Mac Lab', capacity: 55, category: 'study' },
  { id: 'mfcf', name: 'MFCF Computing Lab', capacity: 30, category: 'study' },
  { id: 'qnc', name: 'QNC Basement', capacity: 28, category: 'study' },
  { id: 'slc', name: 'SLC 3rd Floor Lounge', capacity: 50, category: 'study' },
]

export const AUTO_CHECKOUT_MS = 4 * 60 * 60 * 1000 // 4 hours
