export const LOCATIONS = [
  {
    id: 'dp',
    name: 'Dana Porter Library',
    building: 'Dana Porter Library',
    capacity: 300,
    category: 'library',
    description: 'Quiet floors and carrels in Dana Porter.',
    waitzUrl: 'https://waitz.io',
  },
  {
    id: 'dc',
    name: 'Davis Centre Library',
    building: 'Davis Centre Library',
    capacity: 200,
    category: 'library',
    description: 'Main engineering library with group and solo spaces.',
    waitzUrl: 'https://waitz.io',
  },
  {
    id: 'e7',
    name: 'E7 Quiet Study',
    building: 'Engineering 7',
    capacity: 80,
    category: 'study',
    description: 'Silent study rooms on the upper floors of E7.',
  },
  {
    id: 'hlth',
    name: 'Health Sciences Lounge',
    building: 'Health Sciences',
    capacity: 60,
    category: 'study',
    description: 'Open lounge with tables and soft seating.',
  },
  {
    id: 'slc',
    name: 'SLC 3rd Floor Lounge',
    building: 'Student Life Centre',
    capacity: 50,
    category: 'study',
    description: 'Relaxed study area above the Great Hall.',
  },
  {
    id: 'mc',
    name: 'MC Lounge',
    building: 'Mathematics & Computer',
    capacity: 100,
    category: 'study',
    description: 'Common area lounge in the MC building.',
  },
  {
    id: 'bloomberg',
    name: 'Bloomberg Finance Lab',
    building: 'Engineering 7',
    capacity: 25,
    category: 'study',
    description: 'Terminal workstations for finance students.',
  },
]

export const AUTO_CHECKOUT_MS = 4 * 60 * 60 * 1000 // 4 hours
